name: Update README

on:
  push:
  schedule:
    - cron: "0 0/1 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: muesli/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/readme.md.tpl"
          writeTo: "README.md"
      - uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs: Update generated README'
          branch: master
